spring:
  datasource:
    username: simplework_new #root #老数据库：simplework #新数据库：
    password: 53znyPcpNiEJJHAi #mysqladmin #老数据库密码：BRrzyWTzRjR4yc6Y #新数据库密码：
    url: jdbc:mysql://1.116.108.109:3306/simplework_new?characterEncoding = utf-8
  thymeleaf:
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jpa:
    database: MySQL
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  web:
    resources:
      static-locations:
swagger:
  enable:true
mybatis-plus:
    mapper-locations: classpath:mybatis/**/*Mapper.xml