spring:
  datasource:
    username: root # #老数据库：simplework #新数据库：simplework_new
    password: mysqladmin # #老数据库密码：BRrzyWTzRjR4yc6Y #新数据库密码：53znyPcpNiEJJHAi
    url: jdbc:mysql://localhost:3306/simplework?characterEncoding = utf-8
  thymeleaf:
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jpa:
    database: MySQL
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  web:
    resources:
      static-locations: